name: Python testing

on:
  pull_request: 
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev 

jobs:
  test:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"] # ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          pip install flake8 pytest
          pip install -e .[tests] --no-binary pyzmq
          
      - name: Test with pytest
        run: |
          python -m pytest pytest
